=== smithara/swarm-handbook-experiment/json/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/Product",
    "definitions": {
        "Product": {
            "type": "object",
            "additionalProperties": {},
            "properties": {
                "applicable_missions": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "CASSIOPE_e-POP",
                            "CHAMP",
                            "Combined_Mission_Data",
                            "CryoSat-2",
                            "CSES",
                            "GOCE",
                            "GRACE",
                            "GRACE-FO",
                            "Miscellaneous",
                            "Swarm"
                        ]
                    }
                },
                "applicable_spacecraft": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "CASSIOPE_e-POP (Swarm-E)",
                            "CHAMP",
                            "Combined_Mission_Data",
                            "CryoSat-2",
                            "CSES-01",
                            "GOCE",
                            "GRACE-A",
                            "GRACE-B",
                            "GRACE-FO-1",
                            "GRACE-FO-2",
                            "Miscellaneous",
                            "Swarm-A",
                            "Swarm-B",
                            "Swarm-C"
                        ]
                    }
                },
                "changelog": {
                    "type": "string",
                    "contentMediaType": "text/html"
                },
                "description": {
                    "type": "string",
                    "contentMediaType": "text/html"
                },
                "details": {
                    "type": "string",
                    "contentMediaType": "text/html"
                },
                "fast_processing": {
                    "type": "string",
                    "contentMediaType": "text/html"
                },
                "link_files_ftp": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "ftp"
                    ]
                },
                "link_files_http": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "link_hapi": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "link_notebook": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "link_vires_gui": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "definition": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "related_resources": {
                    "type": "string",
                    "contentMediaType": "text/html"
                },
                "thematic_areas": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "Acceleration measurements",
                            "Attitude information",
                            "Core field",
                            "Ephemeris",
                            "Geodesy/Gravity",
                            "GNSS measurements",
                            "HK data",
                            "Ionosphere/Magnetosphere",
                            "Lithosphere",
                            "Magnetic measurements",
                            "Mantle",
                            "Ocean Tides",
                            "Orbit information",
                            "Plasma measurements",
                            "Space Weather",
                            "Thermosphere"
                        ]
                    }
                },
                "variables_table": {
                    "type": "string"
                },
                "input_products": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [],
            "title": "Product"
        }
    }
}

=== smithara/swarm-handbook-experiment/json/catalog/GF_DNSxACC_2_.json
{
    "product_id": "GF_DNSxACC_2_",
    "definition": "Thermosphere mass density at the GRACE-FO satellite locations",
    "applicable_missions": [
        "GRACE-FO"
    ],
    "applicable_spacecraft": [
        "GRACE-FO-1"
    ],
    "thematic_areas": [
        "Ionosphere/Magnetosphere",
        "Thermosphere",
        "Space Weather"
    ],
    "description": "This product contains thermosphere mass density at the GRACE-FO satellite locations",
    "link_files_http": "https://swarm-diss.eo.esa.int/#swarm/Multimission/GRACE-FO/DNS",
    "link_files_ftp": "ftp://swarm-diss.eo.esa.int/Multimission/GRACE-FO/DNS",
    "link_vires_gui": "",
    "link_notebook": "",
    "link_hapi": "",
    "variables_table": "\"Field name\",\"Type\",\"Dimension\",\"Unit\",\"Contents\"\n\"time\",\"CDF_EPOCH\",\"1\",\"ms\",\"Observation time (UTC)\"\n\"altitude\",\"CDF_REAL8\",\"1\",\"m\",\"Observation altitude (GRS80)\"\n\"latitude\",\"CDF_REAL8\",\"1\",\"deg\",\"Observation geodetic latitude\"\n\"longitude\",\"CDF_REAL8\",\"1\",\"deg\",\"Observation longitude \"\n\"local_solar_time\",\"CDF_REAL8\",\"1\",\"h\",\"Local solar time\"\n\"density\",\"CDF_REAL8\",\"1\",\"kg/m3\",\"Mass density\"\n\"density_orbitmean\",\"CDF_REAL8\",\"1\",\"kg/m3\",\"Orbit average of mass density (implemented as moving average)\"\n\"validity_flag\",\"CDF_INT1\",\"1\",\"-\",\"0 = nominal data, 1 = anomalous data\"\n\"validity_flag_orbitmean\",\"CDF_INT1\",\"1\",\"-\",\"0 = nominal data, 1 = anomalous data\"",
    "related_resources": "<ul>\n\t<li><a href=\"https://earth.esa.int/eogateway/activities/toleos\">TOLEOS Project</a></li>\n\t<li><a href=\"http://thermosphere.tudelft.nl/\">TU Delft thermosphere data</a></li>\n</ul>",
    "details": "",
    "changelog": "",
    "fast_processing": ""
}

=== smithara/swarm-handbook-experiment/json/catalog/SW_MIO_SHA_2C.json
{
    "product_id": "SW_MIO_SHA_2C",
    "definition": "Model of non-polar daily geomagnetic variation caused by ionospheric currents, derived in comprehensive chain (CI)",
    "applicable_missions": [
        "Swarm"
    ],
    "applicable_spacecraft": [
        "Swarm-A",
        "Swarm-B",
        "Swarm-C"
    ],
    "thematic_areas": [
        "Ionosphere/Magnetosphere"
    ],
    "description": "Model of non-polar daily geomagnetic variation caused by ionospheric currents, including their variability with season and solar flux, derived in Comprehensive Inversion chain",
    "link_files_http": "https://swarm-diss.eo.esa.int/#swarm/Level2longterm/MIO",
    "link_files_ftp": "ftp://swarm-diss.eo.esa.int/Level2longterm/MIO",
    "link_vires_gui": "https://vires.services?ws=data%3Aapplication/json%2Bgzip%3Bbase64%2CH4sIAMta5mMC/51Va0/bMBT9K1W%2Bro38iF98K4UOJB4TZQOKqig0pngySZWkHQj1v%2B/a9JGGwaCS1cbH95xzc%2B1cvwSlLuZmrH/pojR5Fuy1AhpiHKKg3Qoq86gH2upx9bp0GxCEeQdhGJcI7fkRIoSGLrq2RugeUzBCpdQwGC2lDvLHxKx1WAeTDoVY8p4OuURba05nbvSfekrBxOZ32tGmRZ7OxlXZy7N7M5kVyTLiJRhcxec/Di/i0%2B73bnxyEeN9D89Nae6shuf7xJYaJPJZZU2myzo0TcamegYEO4%2BkSB51BbXyCvvx2WHPPxVJNnFKt5hBqu0Wc38u33Fu86IcJ94n%2BK2rYAFo/6skAEv/1joFqCpm2sl4/7jQZbeRRYc7Pf5RCmtufJqn2m7zgSzYe%2BSFo29ImzK6tLZKhkLxtmj9XQp29CY/8qVKXTdMkTcl9EPTm0ZRhSeJf3JSM9fFxGSTGHvusMEl3u8zzOMGUwJRfoJ3sCOvb7RNV8e%2BXqN2K0If1uc6PrxqmDLYyf9b3uxKHO5EXPjlx2me6axyb3n7Ehh3OoLT4/N4cNSNSc%2BfGzPxLeVb0Dy12czaxehVCNAi%2BZGXZt1fppsJHGeGJMUqFJITTClvtzqEYyQ4IyGLGI2Iku0WjTBBjEchFpJwEnH3CqkpNq22g0JKVUQ4UohJCUygoZAJJATnIBnBL4FNgkARAcS4JAgsIdyJzaZLFaRAQkhouBJRqSRxMoIrzigWXKhIUMEcxinGUgqshFBKKOpUCjN5qPwXFyrKBMaIMiKZUhw7CpEuPZBQFByUFD4dgjgYKRgRgfwlG7nCPXWfTLnVuk%2BgRVez9LV727xqdm7YpmdH8jdG37d/Pz9J7nzvcbviMLIKGq1njRB/OFZRDhvVQeK5kOOWX603jt64fErQYWVSaWtNtfy6unb6kNSul/0imee1ee8hKayp30lng15t9hPqlKQrYLH4C9N3F07ABwAA",
    "link_notebook": "",
    "link_hapi": "",
    "variables_table": "",
    "related_resources": "Part of the CI (comprehensive inversion) chain, related to the \"CM\" model series, see e.g.:\n\nSabaka, T.J., T\u00f8ffner-Clausen, L., Olsen, N. et al. CM6: a comprehensive geomagnetic field model derived from both CHAMP and Swarm satellite observations. Earth Planets Space 72, 80 (2020). https://doi.org/10.1186/s40623-020-01210-5",
    "details": "<table border=\"1\">\n\t<thead>\n\t\t<tr>\n\t\t\t<th>Product identifier</th>\n\t\t\t<th>MIO_SHA_2C</th>\n\t\t</tr>\n\t</thead>\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>Definition</td>\n\t\t\t<td>Spherical harmonic representation of the daily geomagnetic variations at mid and low<br />\n\t\t\tlatitudes (Sq and EEJ) and of its induced counterpart</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Input Data</td>\n\t\t\t<td>MAGx_LR_1R, AUX_DST_2_, AUX_KP__2_, AUX_F10_2_, Q3D_CI_i2_</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Input time span</td>\n\t\t\t<td>All available quiet time observations from the mission</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Spatial representation</td>\n\t\t\t<td>Spherical Harmonics up to degree 60 and order 12 in dipole coordinates</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Time representation</td>\n\t\t\t<td>Fourier Series, seasonal and daily periodicity</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Units</td>\n\t\t\t<td>nT</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Resolution</td>\n\t\t\t<td>1 pT</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Uncertainty</td>\n\t\t\t<td>Refer to product quality report</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Quality indicator</td>\n\t\t\t<td>Statistics of data misfit provided in the validation report</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Data volume</td>\n\t\t\t<td>~130 kB</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Data format</td>\n\t\t\t<td>ASCII listing</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Output data</td>\n\t\t\t<td>Coefficients of SH model in dipole coordinates, with seasonal and diurnal periodicity</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Output time span</td>\n\t\t\t<td>N/A</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Update rate</td>\n\t\t\t<td>First after 1 year, updated every year</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Latency</td>\n\t\t\t<td>1.5 months</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Notes</td>\n\t\t\t<td>&nbsp;</td>\n\t\t</tr>\n\t</tbody>\n</table>",
    "changelog": "",
    "fast_processing": "",
    "input_products": [
        "SW_MAGx_LR_1B"
    ]
}

=== smithara/swarm-handbook-experiment/json/catalog/CS_MAG.json
{
    "product_id": "CS_MAG",
    "definition": "Magnetic measurements derived from Cryosat-2 platform magnetometers",
    "applicable_missions": [
        "CryoSat-2"
    ],
    "applicable_spacecraft": [
        "CryoSat-2"
    ],
    "thematic_areas": [
        "Magnetic measurements"
    ],
    "description": "This product contains calibrated magnetic measurements derived from Cryosat-2 platform magnetometers",
    "link_files_http": "https://swarm-diss.eo.esa.int/#swarm/Multimission/CryoSat-2",
    "link_files_ftp": "ftp://swarm-diss.eo.esa.int/Multimission/CryoSat-2",
    "link_vires_gui": "",
    "link_notebook": "https://notebooks.vires.services/notebooks/03y1_multi-mission-intro",
    "link_hapi": "http://hapi-server.org/servers/#server=VirES-for-Swarm&dataset=CS_OPER_MAG",
    "variables_table": "Variable,Units,Description,Dim,Type\nTimestamp,-,Time stamp,1,CDF_EPOCH\nLatitude,deg,Position in ITRF: Geocentric latitude,1,CDF_DOUBLE\nLongitude,deg,Position in ITRF: Geocentric longitude,1,CDF_DOUBLE\nRadius,m,Position in ITRF: Geocentric Radius,1,CDF_DOUBLE\nB_FGM1,nT,\"calibrated magnetic vector from FGM1, in instrument frame\",3,CDF_DOUBLE\nB_FGM2,nT,\"calibrated magnetic vector from FGM2, in instrument frame\",3,CDF_DOUBLE\nB_FGM3,nT,\"calibrated magnetic vector from FGM3, in instrument frame\",3,CDF_DOUBLE\nB_NEC1,nT,\"calibrated and aligned magnetic vector from FGM1, in NEC (North, East, Center) frame\",3,CDF_DOUBLE\nB_NEC2,nT,\"calibrated and aligned magnetic vector from FGM2, in NEC (North, East, Center) frame\",3,CDF_DOUBLE\nB_NEC3,nT,\"calibrated and aligned magnetic vector from FGM3, in NEC (North, East, Center) frame\",3,CDF_DOUBLE\nB_NEC,nT,\"calibrated and aligned magnetic vector in NEC (North, East, Center) frame, 5 sample (i.e. 20 second) robust average of all 3 FGM, \",3,CDF_DOUBLE\nF,nT,\"magnetic field intensity determined from B_NEC, \",1,CDF_DOUBLE\nB_mod_NEC,nT,\"CHAOS-6 model field (core, crust + magnetosphere), in NEC (North, East, Center) frame\",3,CDF_DOUBLE\nq_NEC_CRF,-,\"Quaternion, transformation: NEC <- CRF\",4,CDF_DOUBLE\nq_error,-,experimental error indicator of attitude given in Quaternion q_NEC_CRF. Bad attitude if > approx 40,1,CDF_DOUBLE",
    "related_resources": "<ul>\n\t<li>Olsen, N., Albini, G., Bouffard, J. et al., Magnetic observations from CryoSat-2: calibration and processing of satellite platform magnetometer data. Earth Planets Space 72, 48 (2020). <a class=\"reference external\" href=\"https://doi.org/10.1186/s40623-020-01171-9\">https://doi.org/10.1186/s40623-020-01171-9</a></li>\n</ul>\n",
    "details": "",
    "changelog": "",
    "fast_processing": ""
}

=== smithara/swarm-handbook-experiment/json/catalog/SW_MLI_SHA_2C.json
{
    "product_id": "SW_MLI_SHA_2C",
    "definition": "Spherical Harmonic Models of the lithospheric field derived in Comprehensive Inversion chain",
    "applicable_missions": [
        "Swarm"
    ],
    "applicable_spacecraft": [
        "Swarm-A",
        "Swarm-B",
        "Swarm-C"
    ],
    "thematic_areas": [
        "Lithosphere"
    ],
    "description": "Spherical Harmonic Models of the lithospheric field derived in Comprehensive Inversion chain",
    "link_files_http": "https://swarm-diss.eo.esa.int/#swarm/Level2longterm/MLI",
    "link_files_ftp": "ftp://swarm-diss.eo.esa.int/Level2longterm/MLI",
    "link_vires_gui": "https://vires.services?ws=data%3Aapplication/json%2Bgzip%3Bbase64%2CH4sIAMta5mMC/51Va0/iQBT9K6RfF5p5dF5%2BQ5TVBF0j7qoY0lQ64mxKS9rCagj/fe%2BMPEpZXSWZQOfMPefcuZ3eWXiFzudmpH/pvDBZ6h01POpj7COv2fBKM9F9nehR%2Bbb04BGEeQthGDcIHbnhI4QGNrqyRugRUzB8pdTAG66kTrJJZDY6rIVJi0IseU%2BH3KCdNaszN/pPNSVvnGSP2tKmeRbPRmXRydInM57l0Spi4fVvwx9Xp9fhRft7O%2Bxdh/jYwXNTmMdEw/NTlBQaJLJZmZhUF1VoGo1M%2BQoIth5RHk10CbVyCsfh5WnHPeVROrZKD5hBqs0Gs38231GWZHkxipyP91uX3hLQ7ldJABZu1zoGqMxn2so4/zDXRbuWRYtbPf5RChtueJHFOtnlA1mw98hLS9%2BStmW0ae2UDPliv2jdQwp2tpcfJl%2Bp1F3NFDlTQj80va8VVTiS%2BCcnNnOdj006DrHjDmpc4vw%2BwzyvMSUQ5Sd4JwfyukYn8frYV2vUbATow/rchae3NVMGb/L/lveHEgcHEZdueTLNUp2WdpcPC8/Y0%2BFd9M7D/lk7JB13bszYtZRv3t6pXS6HbzKA5dFVVphNd5luJ3CYGZIUK19ITjClvNloEY6R4Iz4LGA0IEo2GzTABDEe%2BFhIwknA7QZik28bbQv5lKqAcKQQkxKYQEM%2BE0gIzkEygF8CrwgCRQAQ45IgsIRwKzabrlSQAgkhod1KRKWSxMoIrjijWHChAkEFsxinGEspsBJCKaGoVcnN%2BLl035uvKBMYI8qIZEpxbClE2vRAQlFwUFK4dAjiYKRgBATyl2xoC/fSfjHFTuPuQYMuZ/Fb706yst634SW9WpK7L7qu%2Bbt5L3p0nSedJYnFyDpouJnVQtzRWEdZbFgFieNCjjt%2Blc443HP5lKDFiqjUSWLK1bfVTqbPUeVyOc6jeVaZd56jPDHVG%2Bmy36nMfkKdongNLJd/AXkaI0%2B%2BBwAA",
    "link_notebook": "",
    "link_hapi": "",
    "variables_table": "",
    "related_resources": "Part of the CI (comprehensive inversion) chain, related to the \"CM\" model series, see e.g.:\n\nSabaka, T.J., T\u00f8ffner-Clausen, L., Olsen, N. et al. CM6: a comprehensive geomagnetic field model derived from both CHAMP and Swarm satellite observations. Earth Planets Space 72, 80 (2020). https://doi.org/10.1186/s40623-020-01210-5",
    "details": "<table border=\"1\">\n\t<thead>\n\t\t<tr>\n\t\t\t<th>Product identifier</th>\n\t\t\t<th>MLI_SHA_2C</th>\n\t\t</tr>\n\t</thead>\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>Definition</td>\n\t\t\t<td>Spherical harmonic model of the lithospheric field</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Input Data</td>\n\t\t\t<td>MLI_SHAi2C, MLI_VAL_2_</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Input Time Span</td>\n\t\t\t<td>All available quiet time observations from the mission</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Spatial representation</td>\n\t\t\t<td>Spherical Harmonics from degree 16 to 150</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Time representation</td>\n\t\t\t<td>Snapshot</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Units</td>\n\t\t\t<td>nT</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Resolution</td>\n\t\t\t<td>1 pT</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Uncertainty</td>\n\t\t\t<td>Refer to product quality report</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Quality indicator</td>\n\t\t\t<td>Statistics of data misfits provided in validation report</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Data volume</td>\n\t\t\t<td>~0.5 MB</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Data format</td>\n\t\t\t<td>ASCII table (SHC)</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Output Data</td>\n\t\t\t<td>Gauss coefficients</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Output time span</td>\n\t\t\t<td>N/A (lithospheric field is considered constant over the analysed time range)</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Update rate</td>\n\t\t\t<td>First after 1 year, updated every year</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Latency</td>\n\t\t\t<td>1.5 months</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Notes</td>\n\t\t\t<td>&nbsp;</td>\n\t\t</tr>\n\t</tbody>\n</table>\n",
    "changelog": "",
    "fast_processing": "",
    "input_products": [
        "SW_MAGx_LR_1B"
    ]
}

=== smithara/swarm-handbook-experiment/json/catalog/GFx_FGM_ACAL_CORR.json
{
    "product_id": "GFx_FGM_ACAL_CORR",
    "definition": "Magnetic measurements derived from GRACE-FO platform magnetometers",
    "applicable_missions": [
        "GRACE-FO"
    ],
    "applicable_spacecraft": [
        "GRACE-FO-1",
        "GRACE-FO-2"
    ],
    "thematic_areas": [
        "Magnetic measurements"
    ],
    "description": "This product contains calibrated magnetic measurements derived from GRACE-FO platform magnetometers",
    "link_files_http": "https://swarm-diss.eo.esa.int/#swarm/Multimission/GRACE-FO/Magnetic_data",
    "link_files_ftp": "ftp://swarm-diss.eo.esa.int/Multimission/GRACE-FO/Magnetic_data",
    "link_vires_gui": "",
    "link_notebook": "https://notebooks.vires.services/notebooks/03y1_multi-mission-intro",
    "link_hapi": "http://hapi-server.org/servers/#server=VirES-for-Swarm&dataset=GF1_OPER_FGM_ACAL_CORR",
    "variables_table": "Variable,Units,Description,Dim,Type\nTimestamp,ms,Timestamp,1,CDF_EPOCH\nLatitude,-,-,1,CDF_DOUBLE\nLongitude,-,-,1,CDF_DOUBLE\nRadius,-,-,1,CDF_DOUBLE\nB_FGM,nT,\"[nT] Fluxgate magnetometer, FGM, aligned, vector-vector calibrated and corrected for satellite disturbances, FGM frame\",3,CDF_DOUBLE\nB_NEC,nT,\"[nT] Fluxgate magnetometer, FGM, aligned, vector-vector calibrated and corrected for satellite disturbances, NEC frame\",3,CDF_DOUBLE\nq_NEC_FGM, ,\"Quaternion, transformation: NEC ... FGM\",4,CDF_DOUBLE\ndB_MTQ_FGM,nT,\"[nT] Disturbance field related to magnetorquer, FGM frame\",3,CDF_DOUBLE\ndB_XI_FGM,nT,\"[nT] Disturbance field related to 2nd order non-linearities, FGM frame\",3,CDF_DOUBLE\ndB_NY_FGM,nT,\"[nT] Disturbance field related to 3rd order non-linearities, FGM frame\",3,CDF_DOUBLE\ndB_BT_FGM,nT,\"[nT] Disturbance field related to temperature dependency of offsets, FGM frame\",3,CDF_DOUBLE\ndB_ST_FGM,nT,\"[nT] Disturbance field related to temperature dependency of scale factors, FGM frame\",3,CDF_DOUBLE\ndB_SA_FGM,nT,\"[nT] Disturbance field related to solar array currents, FGM frame\",3,CDF_DOUBLE\ndB_BAT_FGM,nT,\"[nT] Disturbance field related to battery currents, FGM frame\",3,CDF_DOUBLE\nB_FLAG,-,-,1,CDF_UINT1\nLABELS_B,-,LABELS_B,3,CDF_CHAR\nLABELS_BNEC,-,LABELS_BNEC,3,CDF_CHAR\nLABELS_Q,-,LABELS_Q,4,CDF_CHAR",
    "related_resources": "<ul>\n\t<li>Stolle, C., Michaelis, I., Xiong, C. et al., Observing Earth&rsquo;s magnetic environment with the GRACE-FO mission. Earth Planets Space 73, 51 (2021).<br />\n\t<a class=\"reference external\" href=\"https://doi.org/10.1186/s40623-021-01364-w\">https://doi.org/10.1186/s40623-021-01364-w</a></li>\n</ul>\n",
    "details": "",
    "changelog": "",
    "fast_processing": ""
}

=== smithara/swarm-handbook-experiment/json/catalog/SW_EFIx_TCT16.json
{
    "product_id": "SW_EFIx_TCT16",
    "definition": "Swarm Electric Field Instrument (EFI) Thermal Ion Imager (TII) 16Hz Cross-Track ion flow velocity dataset",
    "applicable_missions": [
        "Swarm"
    ],
    "applicable_spacecraft": [
        "Swarm-A",
        "Swarm-B",
        "Swarm-C"
    ],
    "thematic_areas": [
        "Plasma measurements",
        "Space Weather"
    ],
    "description": "Swarm Electric Field Instrument (EFI) Thermal Ion Imager (TII) dataset at 16 Hz cadence containing cross-track ion measurements: the TII L1B data processing is simplified by deriving ion flow velocity components perpendicular to the satellite velocity vector. The data also include the electric field, magnetic field in the same coordinate frame.\n",
    "link_files_http": "https://swarm-diss.eo.esa.int/#swarm/Advanced/Plasma_Data/16Hz_TII_Cross-track_Dataset/",
    "link_files_ftp": "ftp://swarm-diss.eo.esa.int/Advanced/Plasma_Data/16Hz_TII_Cross-track_Dataset/",
    "link_vires_gui": "https://vires.services?ws=data%3Aapplication/json%2Bgzip%3Bbase64%2CH4sIAMta5mMC/8Vbb3OyuhL/Kh1ft04S8of0XbX2nGdu69Pbenqf006HQaSaexAcQG/1mX73mwRREFS0tXScAiHZ/WV3s9lswu9G5IYz4bhPbhiJwG9cnjWMJoRN0Dg/k%2B8814ndwY3wYje8FVEs3780btS7ltVNLp3k0laXa1lDXv59fWvrm7vbnrp0XfW/l/wX1ti1I2sQijddp%2Bdb40hE6vbGs4dWnFTQzS1huW9vlirPFmialtCtLU31ScyTyyK5vI%2BW15nGM7U9Ec%2Btt5ROWz73QzuWPV4WvsrSWIzdR93lRBIvDQQgvQBQ/nqQXUJ0CXGTUfasaKzeoR4wLjG6BGYTU/68InUdjG2xokMuILowQA8CWfHSMJuQGZt0IL4E9BLzJgU4oTMJg8HUiaN24L%2BJ4TSBLEn%2Bbjz%2Bx/p533mw7q7%2BuLJuHyzY0sUzEYm%2B58r7N9uLXEkimMae8N0oWzSxHSkPWQIVDzu0x65UcKQpSMV22voutP2hovQCCQDg/Iyoi0LlBF4QRo6t%2BTT%2B68aND6W9QxtlLEwWxeHU/UgMq9O2Qje62kBxQRU9uhOC0qW1AUQ2QoQUG008OxrbmXatw9p9qJapGjo3P6Qa7r9ODV13Q5wAaHkifd2KqlymvRJiUjXlhIIw9mx/oAXzFG3ogJyf7ZD/X1YQ9kVcNITzM4NsVVxBkL0fHQtZXyTIvMPJIWMKGKSHi1OSDAaudxzNj4zTK2mK9jTNOcmCwe62jlx71YNPEVBSHYnhyBpKP2dJV9V3C/Tg60q99w%2BdW63eH9d3X6fedEoodqTYibk39PvTLUpNJ5u4H2%2BVzVaSH8sZqdB9sF%2Beago7cnRucrzQTlfxJeVsB2LmhkPhDy2YUrBC%2B3%2BfpJKfpwtiowhivFMECsbRjbtHN04ts/Prvpd48F67B9CGZSoDOcIwVUiSFytaOfDdIi23TxXbHEcvaT1flA727c5cRk/zw5scwWX0qX7JEO/45p1RAW7pPDUToRhIf63bzA5vk49AC16CvH6URqWbFQ3tTlVdR5paaN8HkVhFhJP1wwuGiEHKm8wAmDLKpX1eyBvTRKDJOCWGCbjiCw2TY9LkhGCCOdRjZSDCdQh8AZqIAMQ4AZQgYnBIZQTQRKbBDERNRilhGFIm6YMmR0Q%2BQ2QySZYnI286WZKhEBkGNw2KAKcQI0WGcgxNBjkgDDITcVVmMNPAhkkA48zkJlNEQjnL6LWHRI85NyQhxGQDU4OhVHXEwIRIdMCQfTWbEhxlEiCmpkkZdi8g0zJ%2Bv3oXUTbIl5P52I1iezxppK9v7b72/v7U89S49oJ4M/5%2B%2Bd2Yq6o6ulcjXaGclzSeo7Ta6%2Bppo4q2mrSWKnvNFiLdVkLPc1xU5FiJ%2BGvWexWXGmsJqacrbzKy9Z0mk2gFIkioSRHDBHATGFqTmOb%2BmCpjgEgjNAiSmoeM6vA6mo/7gepBwxGh4%2BkFnb3kArW1y%2BWkiKcDdxsAqNlpxmsgqgxIqwaQU8BMbECDoaoMA3%2B4nyMz8n8axUYPcTWGD/ZATKMdApbQc13Rhr%2BWt%2Bq2FnqhYjX%2BN9tZk6z4sGZi5vgmo5Ak3U27X5Wv5Yah5rSFO8v3Z%2Bk28jrVkNYSVxB4RfaZBWMpewpLer9hVLpsw/gOYd%2BqbVwliZrajE6yX7qY7zc8lZraytnMqlLy033M2ZeZWN2GdlA13j/VIrk7HffdcKd/KRFA3rcwWI3h49S/dh0Zvq6dernE80acuNViETtK4hLEg5rHryLH9aOdOE476CWQP4NpeOUPPXeHLPKDXNu%2BYeSBYR0L8bw4cGUUVwsxnsajPUBY3sQSYeQVkFhGXlGVUTy7vtgLwiyRfqkfylksOGRAXGfizi0oeIkoGMwrRdsFyhtGVXdUFUdZqFGlrBqObBat3CJKhmmVsmrsu7tsMS9rXOYNtF/ciIw2XIQf%2BJqxWlDLeNOX8l4vtPNoejvQgA2jJAmc3Ayh4Zg5hIgfjeYpqm2uzqYM65i0innUL5u2DjGHYur1dDPZAbgKWdmagtl8ZreWiS2bkT2h96ymHHmvFxj36fJWNU3zlfJNI61wLaKJZ891yk3n97J90TVrcsfF5OopPfM%2BFPnseLkf2hjsyZKpWEbyvqkikDTnfcoJoYR3qR2ptPV%2BG0pr1bTGzOfW65i5spsM5QLIx2t02wDiIC%2BBivHMdos5Om/0CefTrWQ03d1G89Xpp24FIzlxMiDdBjv5Yvh%2BJKzIqWkRvNru%2BN74oNx9SSzL9NseD7auWFtUsdro%2BdY18ja5zarKbbZPbqddWKebkCdcTX/CFUp0FeU43yfG067I073XE4Z/nxLjoqIYF3uz7aeNIp8iO%2B7WFjlK5p06YscV93ZdMWBn9F5b9NcZzeuK/DqjxbftGHZm798VrHVm8/rCtM5sUdOOTeu9ttxXa/49oWlrUVtY6oTvdeWtFPN5nZGlEy5q2n4pnguqIUgsP3dUwwbMdRTXpIfBTtanFf%2B/JnXJ%2BwYCVldInR7psSZuKIKBcOrKr%2BozEJWhnDY%2BVh/V1BQdqw956oqN1ddDNUXGUuKZb03qiI%2Bl4PchOG2ULKW/G8CXx8ot6%2Bnmzvr1XfFywu7v%2BmLmBMBzXXFzsujfLu9Te9gUwN81%2BtUEwXNd3vVxYjuuE9q7tqwN2XVEuKQKAJUd1ewg5AhjTBGSPwMkR6QJNrFpAEqYgTDBtBoGMdjhYTDAUPoxjBAwUBLgIwIoher0NzERY8vVBTZMqhECzMmB%2B9LbPhgqh8QIpYBLM5P8TJ5AQlLupkkgwghyBrWdcE44l0oBgBAutVUBlEL1pj9qje6EL8ZisfrUQlUcDPRBetv71RPOP%2BvT2%2BrIdOc9dv04PU19fpaeqU6OXW99qw9qB84/ms/L8gMSfcmcC9/6PrJj15MLBTcfmi/xtkJ7FmQ%2BS2mP7NAT2Y%2Bquo/tzNNfEy%2Bw16lBfeQ/svueO/g5c0PPnmsuHx//B2g3SD8dPAAA",
    "link_notebook": "https://notebooks.vires.services/notebooks/03k2_demo-efixtct",
    "link_hapi": "http://hapi-server.org/servers/#server=VirES-for-Swarm&dataset=SW_EXPT_EFIA_TCT16",
    "variables_table": "Variable,Units,Description,Dim,Type\nTimestamp,UTC,Time of observation.,1,CDF_EPOCH\nLatitude,degrees,Geocentric latitude.,1,CDF_REAL4\nLongitude,degrees,Geocentric longitude.,1,CDF_REAL4\nRadius,m,Geocentric radius.,1,CDF_REAL4\nQDLatitude,degrees,Quasi-dipole magnetic latitude.,1,CDF_REAL4\nMLT,hour,Magnetic local time.,1,CDF_REAL4\nVixh,m/s,Along-track ion drift from horizontal TII sensor in satellite-track coordinates.,1,CDF_REAL4\nVixh_error,m/s,Random error estimate for along-track ion drift from horizontal TII sensor in satellite-track coordinates. Negative value indicates no estimate available.,1,CDF_REAL4\nVixv,m/s,Along-track ion drift from vertical TII sensor in satellite-track coordinates.,1,CDF_REAL4\nVixv_error,m/s,Random error estimate for along-track ion drift from vertical TII sensor in satellite-track coordinates. Negative value indicates no estimate available.,1,CDF_REAL4\nViy,m/s,Cross-track horizontal ion drift from horizontal TII sensor in satellite-track coordinates.,1,CDF_REAL4\nViy_error,m/s,Random error estimate for cross-track horizontal ion drift from horizontal TII sensor in satellite-track coordinates. Negative value indicates no estimate available.,1,CDF_REAL4\nViz,m/s,Cross-track vertical ion drift from vertical TII sensor in satellite-track coordinates.,1,CDF_REAL4\nViz_error,m/s,Random error estimate for cross-track vertical ion drift from vertical TII sensor in satellite-track coordinates. Negative value indicates no estimate available.,1,CDF_REAL4\nVsatN,m/s,Satellite velocity N component in north-east-centre coordinates.,1,CDF_REAL4\nVsatE,m/s,Satellite velocity E component in north-east-centre coordinates.,1,CDF_REAL4\nVsatC,m/s,Satellite velocity C component in north-east-centre coordinates.,1,CDF_REAL4\nEhx,mV/m,\"Electric field x component in satellite-track coordinates, derived from -VxB with along-track ion drift from horizontal sensor.\",1,CDF_REAL4\nEhy,mV/m,\"Electric field y component in satellite-track coordinates, derived from -VxB with along-track ion drift from horizontal sensor.\",1,CDF_REAL4\nEhz,mV/m,\"Electric field z component in satellite-track coordinates, derived from -VxB with along-track ion drift from horizontal sensor.\",1,CDF_REAL4\nEvx,mV/m,\"Electric field x component in satellite-track coordinates, derived from -VxB with along-track ion drift from vertical sensor.\",1,CDF_REAL4\nEvy,mV/m,\"Electric field y component in satellite-track coordinates, derived from -VxB with along-track ion drift from vertical sensor.\",1,CDF_REAL4\nEvz,mV/m,\"Electric field z component in satellite-track coordinates, derived from -VxB with along-track ion drift from vertical sensor.\",1,CDF_REAL4\nBx,nT,\"Geomagnetic field x component in satellite-track coordinates, derived from the 1 Hz product.\",1,CDF_REAL4\nBy,nT,\"Geomagnetic field y component in satellite-track coordinates, derived from the 1 Hz product.\",1,CDF_REAL4\nBz,nT,\"Geomagnetic field z component in satellite-track coordinates, derived from the 1 Hz product.\",1,CDF_REAL4\nVicrx,m/s,Ion drift corotation signal x component in satellite-track coorinates. This has been removed from ion drift and electric field.,1,CDF_REAL4\nVicry,m/s,Ion drift corotation signal y component in satellite-track coorinates. This has been removed from ion drift and electric field.,1,CDF_REAL4\nVicrz,m/s,Ion drift corotation signal z component in satellite-track coorinates. This has been removed from ion drift and electric field.,1,CDF_REAL4\nQuality_flags,-,\"Bitwise flag for each velocity component, where a value of 1 for a particular component signifies that calibration was successful, and that the baseline 1-sigma noise level is less than or equal to 100 m/s at 2 Hz. Electric field quality can be assessed from these flags according to -vxB. Bit0 (least significant) = Vixh, bit1 = Vixv, bit2 = Viy, bit3 = Viz. Refer to the release notes for details.\",1,CDF_UINT2\nCalibration_flags,-,Information about the calibration process. Refer to the release notes for details.,1,CDF_UINT4",
    "related_resources": "<p><strong>Product Descriptions:</strong></p>\n\n<ul>\n\t<li><a href=\"https://earth.esa.int/eogateway/documents/20142/37627/swarm-EFI-TII-cross-track-flow-dataset-release-notes.pdf/153449df-b25c-b98e-0052-1e6d25254ff8?version=1.3&t=1610383268866\">Product Release Note</a></li>\n\n</ul>\n",
    "details": "",
    "changelog": "",
    "fast_processing": ""
}
