=== smithara/swarm-handbook-experiment/json/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/Product",
    "definitions": {
        "Product": {
            "type": "object",
            "additionalProperties": {},
            "properties": {
                "applicable_missions": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "CASSIOPE_e-POP",
                            "CHAMP",
                            "Combined_Mission_Data",
                            "CryoSat-2",
                            "CSES",
                            "GOCE",
                            "GRACE",
                            "GRACE-FO",
                            "Miscellaneous",
                            "Swarm"
                        ]
                    }
                },
                "applicable_spacecraft": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "CASSIOPE_e-POP (Swarm-E)",
                            "CHAMP",
                            "Combined_Mission_Data",
                            "CryoSat-2",
                            "CSES-01",
                            "GOCE",
                            "GRACE-A",
                            "GRACE-B",
                            "GRACE-FO-1",
                            "GRACE-FO-2",
                            "Miscellaneous",
                            "Swarm-A",
                            "Swarm-B",
                            "Swarm-C"
                        ]
                    }
                },
                "changelog": {
                    "type": "string",
                    "contentMediaType": "text/html"
                },
                "description": {
                    "type": "string",
                    "contentMediaType": "text/html"
                },
                "details": {
                    "type": "string",
                    "contentMediaType": "text/html"
                },
                "fast_processing": {
                    "type": "string",
                    "contentMediaType": "text/html"
                },
                "link_files_ftp": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "ftp"
                    ]
                },
                "link_files_http": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "link_hapi": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "link_notebook": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "link_vires_gui": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "definition": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "related_resources": {
                    "type": "string",
                    "contentMediaType": "text/html"
                },
                "thematic_areas": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "Acceleration measurements",
                            "Attitude information",
                            "Core field",
                            "Ephemeris",
                            "Geodesy/Gravity",
                            "GNSS measurements",
                            "HK data",
                            "Ionosphere/Magnetosphere",
                            "Lithosphere",
                            "Magnetic measurements",
                            "Mantle",
                            "Ocean Tides",
                            "Orbit information",
                            "Plasma measurements",
                            "Space Weather",
                            "Thermosphere"
                        ]
                    }
                },
                "variables_table": {
                    "type": "string"
                },
                "input_products": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [],
            "title": "Product"
        }
    }
}

=== smithara/swarm-handbook-experiment/json/catalog/SW_AOBxFAC_2F.json
{
    "product_id": "SW_AOBxFAC_2F",
    "definition": "Auroral oval boundaries derived from FACs",
    "applicable_missions": [
        "Swarm"
    ],
    "applicable_spacecraft": [
        "Swarm-A",
        "Swarm-B",
        "Swarm-C"
    ],
    "thematic_areas": [
        "Ionosphere/Magnetosphere",
        "Space Weather"
    ],
    "description": "Auroral oval boundaries, associated with auroral precipitation, estimated from the presence of small-scale (<150 km) field-aligned currents.",
    "link_files_http": "https://swarm-diss.eo.esa.int/#swarm/Level2daily/Latest_baselines/AOB/FAC",
    "link_files_ftp": "ftp://swarm-diss.eo.esa.int/Level2daily/Latest_baselines/AOB/FAC",
    "link_vires_gui": "https://vires.services?ws=data%3Aapplication/json%2Bgzip%3Bbase64%2CH4sIAMta5mMC/8Vcb1PqOhP/Kg6vlUnSpn94Bwr3Oo9yvMr1nqPjdApUyXMLZdrCI57xuz%2BblEpDCxSkxHEspMnuL7ubzWaT%2BLsWeeGcDbxHL4xYMKk1zmpaHeM6qp2fwTvfG8TesMP82AtvWBTD%2B%2Bdah79rOd3k0U4el/xxBTXg8dfVjSs%2B3N70%2BKPr8b%2B95C9zxp4bOcOQvYo6vYkzjljEP3Z8982JkwqiucMc7/XV4eXZAkHTYaK1I6g%2BskXy%2BEge76Plcy7wzFyfxQvnNaVzCd/7oRtDj1eFgovTWX1siZ7N%2Bn3fc%2B7CoO/2GSeTqSDe8e/3ng/U5p7z0GtfOve3D7lCXtDsR4E/iwsKHpcFbd%2BbJ7Cak7eE9PW9eNNpXtZe4Bmzsfcg9JKo67lGEKYXmFxouEe0hm43NKtuI%2BuJt4J3xgXC8NtDeoOgBjHqpk2fvkhdBWOXyXSI2cNag%2BoNHdVtQiU6WOsho0FJg5p1jS7pTMNgOBvE0WUweWVvs0SuQPJ37eEf58dd%2B965bf7RdG7uHdwSxXMWMS64xtmr60cekAhmsc8mXpQtmroDLu3GGeY83NAde2CFkaAA1gcC459Cd/LGKT1jihA6P6P8wVENAj8Io4Er%2BNT%2B68W1Ty7GfRtlhgEUxeHM%2B0ysH/QcelFzDcWFwekZWyEs7UxqB40IpflGU9%2BNxm6mXWu/dp%2B8ZaqGduca1HB3PDV0vTVxIiTkScRzI6pimfYKiIFqigkFYey7k6EQzGO0pgN6frZF/n87Qdhncd4Qzs80ulFxOUH2rtsOcY4kSNkrSshMDgwb%2B4sTSAZDzz%2BM5mfGMxc0JTuaSp48Z7DbrUNqz3vwLQJcqiP2NnLewM854Kr6Xo4efvlS7919%2B0ao9/rq9njqTeetfEfynVj4b5P%2BbINS0xkx7scbZbOR5Ody2sx1H%2B2WJ59nDxyd6xwvhNPlfGkx2yHMmeEbm7w5OKXghO7/vklFDiZyYjMI1vWtIuAwDm7cPbhxapntn3e9xIP3LnuIHMkyeeAky5V8efDtMi02UB6BHUYvab34KBztm705xHiL/ZscwGX0rX5BIHp48/YoB7dwopqzkA3BYYs28/3byHFyzk3Ql8/C2Hm9opbxp2K6vG7BdHn74JDOscK/fFCe9%2Bl7hHNSOL9OydBKhlcQwx%2B3m/J6ISdmumdEIK9H1smZuxx5fo2TM7AdFOTlzh79%2BSxYGq03t1FJNcFKqlhNXE4HaIkv0NbWAGA0u0d1p7l/uwLFJp0bAKLQvQsi9rX4mq6%2BPF%2BYFjIJRXXd0HREddM%2BP7swTduyEa1DkU0wMWwqIjvbsA1SR4hapklMoZQhC1cLTiBiUmJRmxKDmjqybRPibSjUTaCoI2LrukU0HTigOrw3YaFoIIqhDItROZsmZCgBKDYG7oZtIUI4FQoNAZWNETDQNIuXGSY2bf5HQwDfFohCCOnihIyJDBPgWEjToBOUJnyRqVs676FBLGxBIakTgnTdQNBZijSseRfYEB7tvfnOouyaGmLnsRfF7nhaS1/fuH0RbE1mvs9NwA/i9eXu8%2B/agldNciTL5fqioPGCpNVevr6tVREWkNbiZS/ZQiLafr5kbTG/%2BF51QvgSfzpyxSdBJhEdJpgaICFTpwhUoNlCkYb0I5RrgjWA/ijoFmPTECqIFuN%2BwDHXBiwcJMkKd8kFC6O8ATDxbOhtAoAFO8F4BYSXgYXaCNsGMi0dNAWWW5JhMHnbzdHU5J/EeuUe6uUY3rtDNou2CBigS10R9rySN%2B%2B2EHquYjn%2Bnc2saVZ8umBiSXwtQwy4pLtp98vydbwwFJw2cDfl/oixbazpVEBaSZxDsEuyz6RQCtkbuKD3a0YlytaMbx/2LWXjKsmvKjM6YL90Mac3PJ5R3sjZyqoS%2BIk%2BSvZlJVa3ph1SjvcPnjbqzsZ9L9zqXwoEIPsWE5dj%2BDCbXHkDCEZWTr1Y4rIRJ241X2QeJHEAcc8n22Y08CbRVhzVDnoA8mcwC1fRX7Es5EEubF/TZGA6L5TNQqN6aRTNDzaexaMdQEzZxBJhyApILENWVGkUT96E7QRhFUi/0A9JFov2GRBXmdhwAwq7QBQmlpUi7ILIhlHWHZXFURRqlCkrhyObVy62iIJhWqasHPvuNluUZa0XeQPhF9ciozUXMQkmgjFfHkG8OQF5r5ZNMpreFjRozShpAkeaIQQcS0JI7IPRPEbK5upsEl3FpJXfWTjatLWPOeQ3I6qbyfbAldunUBTMynsdSia27B5Fhd6znHLgs1hg3KXLW940zeDDm1pa4YpFU99diHSIyNZk%2ByJqKnLH%2Be2GKj3zLhTyflGxH1ob7MmSKV9GZd9UEki6C1TlhFDAu9CO%2BEbObhtKaylaY8q7TSpmruy2W7EA5HjN2DSAbCRLoGQ8s9liDs4bfcP5dEsZTXe70Rw7/dQtYSQVJwPSjeHKF8N3I%2BZEA0WL4K/9v9PGB8XuC7As0287PNiqorKo4mvn86Rr5E1ym5eV23yX3KpdWKe78hWupr/hCgFdSTkudomx2hV5ehihwvDvW2L8KCnGj53Z9mqjyMfIjbvKIkdg3lYRO35xv1QVA7ZH78qiv/ZooSrya48%2BTrZj2J6/nypYa88X6sK09vxD0Y5N611Z7qu1OE1o2vpQFpYOwndVeSvOfKEyshyEH4q2X/IH5RQEicUH8RRswOSPqR3Rm%2B6RzM0fL1PjagsOqp3e7eYP%2B6nwwMVnBit3yOmRPCWOCZg77R3xepXOKT1XWKFL2meHpblTGtV6pw1nhSsM5/fcf5IOHqsI9a%2BiWJGpDreyrnb6/M9UlUV2MDJVpUTSI5nO1AtZMGQDVftj4gxbaSjV5jf4XWZF2Q1%2Bf1pVboNf2laU2QCJZ27PqnB6IPhdCKrNcoD0twM4eq6j5Tx2bp2fp8p3JOx%2BqQvEEwBPqvIeSdJ2s7yr9rApgF8K/WqC4EmVd/3j7sFJ78RsU0S1I11C8etkw11i%2B3SqUX/T/lFK5FUPfgnHL0U%2BQALxpGwV/jB1B94gdLedvNMMfkHMBlYIGTDexajD2Ca6rhuEwK%2BGSLIk1y3d0pBBTY3oVDfKYWDDLcNPRzqG6VwnBGkkyVMSigwDw19CLWKayySprlmGQIh0m%2B55vG7TfwIohmRSw0A2SBr4WXYCiYAyLItiohNsm1i4S9umtg2aQohSGwZLCVAc1av4lzrRLZuwMfv4us3HKw6Hwl5c/2ePDf5d3RPjN7/a77E3ibOXwpLrYwXl4lZZMPhX0H4W24mZ62b5F5Ebez4sjz05j7hE1QrdeZC5EXk5ckOfZS%2B3dh8uM9/%2BnvqBu9rHFHcIIxdWucMfcy/03YXg8vn5f6/XFNWBSAAA",
    "link_notebook": "https://notebooks.vires.services/notebooks/03h3_demo-aebs-aobxfac",
    "link_hapi": "http://hapi-server.org/servers/#server=VirES-for-Swarm&dataset=SW_OPER_AOBAFAC_2F",
    "variables_table": "Variable,Units,Description,Dim,Type\nt, ,\"Time of observation, UTC\",1,CDF_EPOCH\nLatitude,deg,Position in ITRF - Geocentric latitude,1,CDF_DOUBLE\nLongitude,deg,Position in ITRF - Geocentric longitude,1,CDF_DOUBLE\nRadius,m,Position in ITRF - Geocentric radius (from the Earth center),1,CDF_DOUBLE\nLatitude_QD,deg,Quasi-dipole latitude,1,CDF_DOUBLE\nLongitude_QD,deg,Quasi-dipole longitude,1,CDF_DOUBLE\nMLT,hour,Magnetic Local Time (QD),1,CDF_DOUBLE\nBoundary_Flag,,Indicator for equatorward (=1) or poleward (=2) boundary,1,CDF_UINT1\nQuality,,\"Quality indicator of equatorward/poleward boundary (Pa, Sigma)\",2,CDF_DOUBLE\nPair_Indicator,,\"Indicator of equatorward/poleward boundary of auroral oval. If the auroral oval boundaries are detectable as one pair, the pair indicator represents the record of previous (-1) or next (1) equatorward/poleward boundary within one pair; otherwise, the pair indicator is set to 0\",1,CDF_INT1\n",
    "related_resources": "<ul>\n<li><a href=\"https://earth.esa.int/eogateway/activities/swarm-aebs\">Activity: Auroral Electrojet and auroral Boundaries estimated from Swarm observations</a></li>\n<li><a href=\"https://earth.esa.int/eogateway/documents/20142/37627/Swarm-AEBS-product-definition.pdf\">Swarm-AEBS Product Definition</a></li>\n<li><a href=\"https://earth.esa.int/eogateway/documents/20142/37627/Swarm-AEBS-processing-algorithm-description.pdf\">Swarm-AEBS Description of the Processing Algorithm</a></li>\n<li><a href=\"https://earth.esa.int/eogateway/documents/20142/37627/Validation-auroral-electrojet-auroral-boundaries-estimated-from-swarm.pdf\">Validation of Auroral Electrojet and Auroral Boundaries estimated from Swarm observations</a></li>\n</ul>\n",
    "details": "<table border=\"1\">\n<tbody>\n  <tr>\n    <td> Product identifier  </td>\n    <td> AOBxFAC_2F  </td>\n  </tr>\n  <tr>\n    <td> Definition  </td>\n    <td> Auroral Oval Boundaries using the FAC method  </td>\n  </tr>\n  <tr>\n    <td> Input Data  </td>\n    <td> FACxTMS_2F<sup>1</sup>  </td>\n  </tr>\n  <tr>\n    <td> Input Time Span  </td>\n    <td> Up to one year  </td>\n  </tr>\n  <tr>\n    <td> Spatial representation  </td>\n    <td> One geographic and quasi-dipole latitude/longitude as well as magnetic local time for each output value at the nearest magnetic-field measurement.  </td>\n  </tr>\n  <tr>\n    <td> Time representation  </td>\n    <td> One timestamp for each boundary represented by the geographic and quasi-dipole latitude/longitude as well as magnetic local time.  </td>\n  </tr>\n  <tr>\n    <td> Units  </td>\n    <td> Degrees  </td>\n  </tr>\n  <tr>\n    <td> Resolution  </td>\n    <td> Full resolution (Double precision)  </td>\n  </tr>\n  <tr>\n    <td> Uncertainty  </td>\n    <td> 3 deg, c.f. Xiong, C. and L\u00fchr, H., doi: 10.5194/angeo-32-623-2014  </td>\n  </tr>\n<tr>\n    <td> Quality indicator </td>\n    <td>\n<table border=\"1\">\n<tbody>\n  <tr>\n    <td>Value</td>\n    <td>Meaning</td>\n  </tr>\n  <tr>\n    <td>Pa</td>\n    <td>Slop of linear fit of S value. Users are suggested to use boundaries with pa larger than 0.2</td>\n  </tr>\n  <tr>\n    <td>Sigma</td>\n    <td>The standard deviation of the linear fit of S value. Users are suggested to use boundaries with \u03c3 less than 0.4. See SW-DS-GFZ-GS-001_AEBS_DPA Swarm-AEBS Description of the Processing Algorithm, for the S value definition</td>\n  </tr>\n</tbody>\n</table>\n</td>\n  </tr>\n  <tr>\n    <td> Data volume  </td>\n    <td> Up to 2.5 MB  </td>\n  </tr>\n  <tr>\n    <td> Data format  </td>\n    <td> CDF  </td>\n  </tr>\n  <tr>\n    <td> Output time span  </td>\n    <td> Up to one year<sup>2</sup>  </td>\n  </tr>\n  <tr>\n    <td> Update rate  </td>\n    <td> Daily  </td>\n  </tr>\n  <tr>\n    <td> Latency  </td>\n    <td> &lt; 1 day  </td>\n  </tr>\n  <tr>\n    <td> Notes  </td>\n    <td> <sup>1</sup> Version information of Input Data are available in the CDF global attributes. <br> <sup>2</sup> Product always contain data from the start of the first oval crossing of the year until the end of the last oval crossing starting that year, i.e., may contain data from the next year if oval crossing occurs around midnight.  </td>\n  </tr>\n</tbody>\n</table>",
    "changelog": "",
    "fast_processing": "",
    "input_products": [
        "SW_FACxTMS_2F"
    ]
}

=== smithara/swarm-handbook-experiment/json/catalog/SW_MLI_SHA_2E.json
{
    "product_id": "SW_MLI_SHA_2E",
    "definition": "Final map of the lithospheric field from the Revised Spherical Cap Harmonic analysis (R-SCHA) Dedicated Lithospheric Inversion, expressed in terms of high degree Spherical Harmonics",
    "applicable_missions": [
        "CHAMP",
        "Miscellaneous",
        "Swarm"
    ],
    "applicable_spacecraft": [
        "CHAMP",
        "Miscellaneous",
        "Swarm-A",
        "Swarm-B",
        "Swarm-C"
    ],
    "thematic_areas": [
        "Lithosphere"
    ],
    "description": "Final map of the lithospheric field from the Revised Spherical Cap Harmonic analysis (R-SCHA) Dedicated Lithospheric Inversion, expressed in terms of high degree Spherical Harmonics",
    "link_files_http": "https://swarm-diss.eo.esa.int/#swarm/Level2longterm/MLI",
    "link_files_ftp": "ftp://swarm-diss.eo.esa.int/Level2longterm/MLI",
    "link_vires_gui": "",
    "link_notebook": "",
    "link_hapi": "",
    "variables_table": "",
    "related_resources": "",
    "details": "<table border=\"1\">\n\t<thead>\n\t\t<tr>\n\t\t\t<th>Product identifier</th>\n\t\t\t<th>MLI_SHA_2E</th>\n\t\t</tr>\n\t</thead>\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>Definition</td>\n\t\t\t<td>Final map of the lithospheric field from the Revised Spherical Cap Harmonic analysis (R-SCHA) Dedicated Lithospheric Inversion, expressed in terms of high degree Spherical Harmonics</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Input Data</td>\n\t\t\t<td>MAGx_LR_1B, AUX_KP__2_, AUX_DST_2_, AUX_F10_2_, AUX_IMF_2_, AUX_MTI_2_, AUX_LIT_2_, AUX_COR_2_, IBIxTMS_2_, MCO_SHAi2D, MCO_SHA_2F, MMA_SHAi2C, MMA_SHA_2F, MCO_SHAi2C, MIO_SHAi2C, MIO_SHAi2D, MSW_EULi2C, MSW_EULi2D</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Input Time Span</td>\n\t\t\t<td>One to four years of full Swarm data set</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Spatial representation</td>\n\t\t\t<td>Spherical harmonics from degree 16 to 200 (version 0502), 300 (version 0601), 1050 (version 0701), 1319 (version 0801)</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Time representation</td>\n\t\t\t<td>Snapshot</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Units</td>\n\t\t\t<td>nT</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Resolution</td>\n\t\t\t<td>1 pT</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Uncertainty</td>\n\t\t\t<td>Refer to product quality report</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Quality indicator</td>\n\t\t\t<td>Statistics of data misfits provided in validation report</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Data volume</td>\n\t\t\t<td>~3 MB</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Data format</td>\n\t\t\t<td>ASCII table (SHC)</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Output Data</td>\n\t\t\t<td>Gauss coefficients</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Output time span</td>\n\t\t\t<td>N/A (lithospheric field is considered constant over the analysed time range)</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Update rate</td>\n\t\t\t<td>One model every year</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Latency</td>\n\t\t\t<td>One month</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Notes</td>\n\t\t\t<td>The product has the same format as the other lithospheric field models, but at a higher SH degree to be used for mapping purpose only. SH Gauss coefficients are here a mean to store the map, but the product itself is a map. The map should not be computed at altitudes lower than the minimum altitude of Swarm measurements</td>\n\t\t</tr>\n\t</tbody>\n</table>\n",
    "changelog": "",
    "fast_processing": "",
    "input_products": [
        "SW_IBIxTMS_2F",
        "SW_MAGx_LR_1B",
        "SW_MCO_SHA_2C",
        "SW_MCO_SHA_2D",
        "SW_MCO_SHA_2F",
        "SW_MIO_SHA_2C",
        "SW_MIO_SHA_2D",
        "SW_MMA_SHA_2C",
        "SW_MMA_SHA_2F"
    ]
}

=== smithara/swarm-handbook-experiment/json/catalog/GR_WNDxACC_2_.json
{
    "product_id": "GR_WNDxACC_2_",
    "definition": "Thermosphere crosswind at the GRACE satellite locations",
    "applicable_missions": [
        "GRACE"
    ],
    "applicable_spacecraft": [
        "GRACE-A",
        "GRACE-B"
    ],
    "thematic_areas": [
        "Ionosphere/Magnetosphere",
        "Thermosphere",
        "Space Weather"
    ],
    "description": "This product contains thermosphere crosswind at the GRACE satellite locations",
    "link_files_http": "https://swarm-diss.eo.esa.int/#swarm/Multimission/GRACE/WND",
    "link_files_ftp": "ftp://swarm-diss.eo.esa.int/Multimission/GRACE/WND",
    "link_vires_gui": "",
    "link_notebook": "",
    "link_hapi": "",
    "variables_table": "\"Field name\",\"Type\",\"Dimension\",\"Unit\",\"Contents\"\n\"time\",\"CDF_EPOCH\",\"1\",\"ms\",\"Observation time (UTC)\"\n\"altitude\",\"CDF_REAL8\",\"1\",\"m\",\"Observation altitude (GRS80)\"\n\"latitude\",\"CDF_REAL8\",\"1\",\"deg\",\"Observation geodetic latitude\"\n\"longitude\",\"CDF_REAL8\",\"1\",\"deg\",\"Observation longitude \"\n\"local_solar_time\",\"CDF_REAL8\",\"1\",\"h\",\"Local solar time\"\n\"crosswind\",\"CDF_REAL8\",\"1\",\"m/s\",\"Crosswind magnitude\"\n\"crosswind_direction\",\"CDF_REAL8\",\"3\",\"-\",\"Direction of the crosswind in local North-East-Down frame (unit vector)\"\n\"validity_flag\",\"CDF_INT1\",\"1\",\"-\",\"0 = nominal data, 1 = anomalous data\"",
    "related_resources": "<ul>\n\t<li><a href=\"https://earth.esa.int/eogateway/activities/toleos\">TOLEOS Project</a></li>\n\t<li><a href=\"http://thermosphere.tudelft.nl/\">TU Delft thermosphere data</a></li>\n</ul>",
    "details": "",
    "changelog": "",
    "fast_processing": ""
}

=== smithara/swarm-handbook-experiment/json/catalog/SW_EGF_SHA_2_.json
{
    "product_id": "SW_EGF_SHA_2_",
    "definition": "Monthly gravity field of the Earth",
    "applicable_missions": [
        "Swarm"
    ],
    "applicable_spacecraft": [
        "Swarm-A",
        "Swarm-B",
        "Swarm-C"
    ],
    "thematic_areas": [
        "Geodesy/Gravity"
    ],
    "description": "Monthly average of Earth's gravity field, i.e. with an implicit epoch located at the middle of the calendar month",
    "link_files_http": "https://swarm-diss.eo.esa.int/#swarm/Level2longterm/EGF",
    "link_files_ftp": "ftp://swarm-diss.eo.esa.int/Level2longterm/EGF",
    "link_vires_gui": "",
    "link_notebook": "",
    "link_hapi": "",
    "variables_table": "",
    "related_resources": "",
    "details": "<table border=\"1\">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>Product identifier</td>\n\t\t\t<td>EGF_SHA_2_</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Definition</td>\n\t\t\t<td>Monthly gravity field of the Earth</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Input data</td>\n\t\t\t<td>GPSA_RO_1B, GPSB_RO_1B, GPSC_RO_1B, STRAATT_1B, STRBATT_1B, STRCATT_1B</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Input time span</td>\n\t\t\t<td>1 calendar month</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Spatial representation</td>\n\t\t\t<td>Spherical harmonic coefficients</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Time representation</td>\n\t\t\t<td>Monthly average of Earth&#39;s gravity field, i.e. with an implicit epoch located at the middle of the calendar month</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Units</td>\n\t\t\t<td>See output data</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Resolution</td>\n\t\t\t<td>12 significant digits in scientific notation</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Uncertainty</td>\n\t\t\t<td>Typically 1-2 mm geoid height or 1-2 cm Equivalent Water Height discrepancy w.r.t. GRACE over land areas during low solar activity periods, considering Gaussian smoothing with 750km spherical cap radius</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Quality indicator</td>\n\t\t\t<td>RMS over ocean areas that are 6 degrees away from coast lines, after removing long-term trend, annual and semi-annual variations estimated from monthly un-weighted averages of numerous GRACE models (AIUB02, CSR05, GRGS03, ITSG14, GFZ05a, JPL05 and TNJ01)</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Data volume</td>\n\t\t\t<td>20 Kb</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Data format</td>\n\t\t\t<td>ASCII file with Stokes Coefficients following the ICGEM-format (http://icgem.gfz-potsdam.de/ICGEM-Format-2011.pdf)</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Output data</td>\n\t\t\t<td>Degree, order, cosine coefficient, sine coefficient (columns 5 and 6 set to zero)</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Output time span</td>\n\t\t\t<td>1 calendar month</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Update rate</td>\n\t\t\t<td>Quarterly</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Latency</td>\n\t\t\t<td>5 months</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Notes</td>\n\t\t\t<td>- Stokes coefficients available up to degree 40<br />\n\t\t\t&nbsp;- No smoothing applied<br />\n\t\t\t&nbsp;- GRACE comparison indicates that there is little useful geophysical signal above roughly degree 12, i.e. it suggest the signal-to-noise ratio drops below 1 at those degrees and above<br />\n\t\t\t&nbsp;- Further product details in Swarm ITT1.1 TN-01</td>\n\t\t</tr>\n\t</tbody>\n</table>\n",
    "changelog": "",
    "fast_processing": "",
    "input_products": [
        "SW_GPSx_RO_1B",
        "SW_STRxATT_1B"
    ]
}

=== smithara/swarm-handbook-experiment/json/catalog/GR_NE__KBR_2F.json
{
    "product_id": "GR_NE__KBR_2F",
    "definition": "Time series of the averaged electron density (Ne) between GRACE 1 and 2 satellites",
    "applicable_missions": [
        "GRACE"
    ],
    "applicable_spacecraft": [
        "GRACE-A",
        "GRACE-B"
    ],
    "thematic_areas": [
        "Space Weather",
        "Ionosphere/Magnetosphere"
    ],
    "description": "This product contains the time series of the averaged electron density (Ne) between GRACE 1 and 2 satellites",
    "link_files_http": "https://swarm-diss.eo.esa.int/#swarm/Multimission/GRACE/NE",
    "link_files_ftp": "ftp://swarm-diss.eo.esa.int/Multimission/GRACE/NE",
    "link_vires_gui": "",
    "link_notebook": "",
    "link_hapi": "",
    "variables_table": "\"Variable Name\",\"Type\",\"Dim\",\"Unit\",\"Description\"\n\"Timestamp\",\"CDF_EPOCH\",\"1\",\"ms\",\"Time of observation, UTC\"\n\"Latitude\",\"CDF_DOUBLE\",\"1\",\"deg\",\"Middle point position between GRACE 1 and 2 satellites in ITRF \u2013 Geocentric latitude\"\n\"Longitude\",\"CDF_DOUBLE\",\"1\",\"deg\",\"Middle point position between GRACE 1 and 2 satellites in ITRF \u2013 Geocentric longitude\"\n\"Radius\",\"CDF_DOUBLE\",\"1\",\"m\",\"Middle point position between GRACE 1 and 2 satellites in ITRF \u2013 Geocentric radius (from the Earth centre)\"\n\"LEO_Position\",\"CDF_DOUBLE\",\"2x3\",\"m\",\"X-, Y-, Z-coordinates of the GRACE 1 and 2 satellites\"\n\"Distance\",\"CDF_DOUBLE\",\"1\",\"m\",\"Distance between GRACE 1 and 2 satellites\"\n\"Relative_Hor_TEC\",\"CDF_DOUBLE\",\"1\",\"TECU\",\"Relative horizontal TEC between GRACE 1 and 2 satellites\"\n\"Relative_Ne2\",\"CDF_DOUBLE\",\"1\",\"m-3\",\"Mean relative electron density of the area between GRACE 1 and 2 satellites\"\n\"Absolute_Ne\",\"CDF_DOUBLE\",\"1\",\"m-3\",\"Electron density between GRACE 1 and 2 satellites\"",
    "related_resources": "<ul>\n\t<li><a href=\"https://earth.esa.int/eogateway/activities/tiro\">TIRO Project</a></li>\n</ul>",
    "details": "",
    "changelog": "",
    "fast_processing": ""
}

=== smithara/swarm-handbook-experiment/json/catalog/SW_EFIxLPI_1B.json
{
    "product_id": "SW_EFIxLPI_1B",
    "definition": "Electric field instrument (Langmuir probe measurements at 1Hz)",
    "applicable_missions": [
        "Swarm"
    ],
    "applicable_spacecraft": [
        "Swarm-A",
        "Swarm-B",
        "Swarm-C"
    ],
    "thematic_areas": [
        "Plasma measurements",
        "Space Weather"
    ],
    "description": "The EFIX_LP_1B Product contains plasma data from the Langimur Probe (LP) of the Electrical Field Instrument (EFI). The plasma product encompasses the plasma density and temperature. Data is provided at 2 Hz rate. The time instant are determined by the EFI instruments. No interpolation of the EFI data is performed, neither to shift the measurements in time nor to fill any gaps.",
    "link_files_http": "https://swarm-diss.eo.esa.int/#swarm/Level1b/Latest_baselines/EFIxLPI",
    "link_files_ftp": "ftp://swarm-diss.eo.esa.int/Level1b/Latest_baselines/EFIxLPI",
    "link_vires_gui": "",
    "link_notebook": "",
    "link_hapi": "",
    "variables_table": "Variable,Units,Description,Dim,Type\nTimestamp,-,Time stamp,1,CDF_EPOCH\nSyncStatus,-,Synchronization status,1,CDF_UINT2\nLatitude,deg,Geocentric latitude,1,CDF_DOUBLE\nLongitude,deg,Geocentric longitude,1,CDF_DOUBLE\nRadius,m,Distance from the Earth\u2019s center,1,CDF_DOUBLE\nU_orbit,m/s,Spacecraft velocity in the ITRF,1,CDF_DOUBLE\nNe,cm-3,Plasma density (electron),1,CDF_DOUBLE\nNe_error,cm-3,Error estimate of plasma density (ne),1,CDF_DOUBLE\nTe,K,Plasma electron temperature,1,CDF_DOUBLE\nTe_error,K,Error estimate of plasma electron temperature (T_elec),1,CDF_DOUBLE\nVs,V,Spacecraft potential,1,CDF_DOUBLE\nVs_error,V,Error estimate of spacecraft potential (U_pol),1,CDF_DOUBLE\nFlags_LP,-,\"Flags indicating the source/method of LP measurements (Ne, Te, Vs)\",1,CDF_UINT1\nFlags_Ne,-,Flags characterizing the plasma density measurement,1,CDF_UINT1\nFlags_Te,-,Flags characterizing the electron temperature measurement,1,CDF_UINT1\nFlags_Vs,-,Flags characterizing the spacecraft potential measurement,1,CDF_UINT1\n",
    "related_resources": "",
    "details": "",
    "changelog": "",
    "fast_processing": ""
}

=== smithara/swarm-handbook-experiment/json/catalog/GRACE_x_MAG.json
{
    "product_id": "GRACE_x_MAG",
    "definition": "Magnetic measurements derived from GRACE platform magnetometers",
    "applicable_missions": [
        "GRACE"
    ],
    "applicable_spacecraft": [
        "GRACE-A",
        "GRACE-B"
    ],
    "thematic_areas": [
        "Magnetic measurements"
    ],
    "description": "This product contains calibrated magnetic measurements derived from GRACE platform magnetometers",
    "link_files_http": "https://swarm-diss.eo.esa.int/#swarm/Multimission/GRACE/Magnetic_data",
    "link_files_ftp": "ftp://swarm-diss.eo.esa.int/Multimission/GRACE/Magnetic_data",
    "link_vires_gui": "",
    "link_notebook": "https://notebooks.vires.services/notebooks/03y1_multi-mission-intro",
    "link_hapi": "http://hapi-server.org/servers/#server=VirES-for-Swarm&dataset=GRACE_A_MAG",
    "variables_table": "Variable,Units,Description,Dim,Type\nTimestamp,-,Time stamp,1,CDF_EPOCH\nLatitude,deg,Position in ITRF: Geocentric latitude,1,CDF_DOUBLE\nLongitude,deg,Position in ITRF: Geocentric longitude,1,CDF_DOUBLE\nRadius,m,Position in ITRF: Geocentric Radius,1,CDF_DOUBLE\nB_FGM,nT,\"calibrated magnetic vector from FGM, in instrument frame\",3,CDF_DOUBLE\nB_NEC_raw,nT,\"calibrated and aligned magnetic vector in NEC (North, East, Center) frame\",3,CDF_DOUBLE\nB_NEC,nT,\"calibrated and aligned magnetic vector in NEC (North, East, Center) frame, 11 sample (i.e. 11 second) robust average\",3,CDF_DOUBLE\nF,nT,magnetic field intensity determined from B_NEC,1,CDF_DOUBLE\nq_NEC_CRF,-,\"Quaternion, transformation: NEC <- CRF\",4,CDF_DOUBLE\nq_error,-,experimental error indicator of attitude given in Quaternion q_NEC_CRF. Bad attitude if > approx 40,1,CDF_DOUBLE",
    "related_resources": "<ul>\n\t<li>Olsen, N., Magnetometer data from the GRACE satellite duo. Earth Planets Space 73, 62 (2021).<br />\n\t<a class=\"reference external\" href=\"https://doi.org/10.1186/s40623-021-01373-9\">https://doi.org/10.1186/s40623-021-01373-9</a></li>\n</ul>\n",
    "details": "",
    "changelog": "",
    "fast_processing": ""
}
