=== smithara/swarm-handbook-experiment/json/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/Product",
    "definitions": {
        "Product": {
            "type": "object",
            "additionalProperties": {},
            "properties": {
                "applicable_missions": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "CASSIOPE_e-POP",
                            "CHAMP",
                            "Combined_Mission_Data",
                            "CryoSat-2",
                            "CSES",
                            "GOCE",
                            "GRACE",
                            "GRACE-FO",
                            "Miscellaneous",
                            "Swarm"
                        ]
                    }
                },
                "applicable_spacecraft": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "CASSIOPE_e-POP (Swarm-E)",
                            "CHAMP",
                            "Combined_Mission_Data",
                            "CryoSat-2",
                            "CSES-01",
                            "GOCE",
                            "GRACE-A",
                            "GRACE-B",
                            "GRACE-FO-1",
                            "GRACE-FO-2",
                            "Miscellaneous",
                            "Swarm-A",
                            "Swarm-B",
                            "Swarm-C"
                        ]
                    }
                },
                "changelog": {
                    "type": "string",
                    "contentMediaType": "text/html"
                },
                "description": {
                    "type": "string",
                    "contentMediaType": "text/html"
                },
                "details": {
                    "type": "string",
                    "contentMediaType": "text/html"
                },
                "fast_processing": {
                    "type": "string",
                    "contentMediaType": "text/html"
                },
                "link_files_ftp": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "ftp"
                    ]
                },
                "link_files_http": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "link_hapi": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "link_notebook": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "link_vires_gui": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "definition": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "related_resources": {
                    "type": "string",
                    "contentMediaType": "text/html"
                },
                "thematic_areas": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "Acceleration measurements",
                            "Attitude information",
                            "Core field",
                            "Ephemeris",
                            "Geodesy/Gravity",
                            "GNSS measurements",
                            "HK data",
                            "Ionosphere/Magnetosphere",
                            "Lithosphere",
                            "Magnetic measurements",
                            "Mantle",
                            "Ocean Tides",
                            "Orbit information",
                            "Plasma measurements",
                            "Space Weather",
                            "Thermosphere"
                        ]
                    }
                },
                "variables_table": {
                    "type": "string"
                },
                "input_products": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [],
            "title": "Product"
        }
    }
}

=== smithara/swarm-handbook-experiment/json/catalog/SW_SC_xDYN_1B.json
{
    "product_id": "SW_SC_xDYN_1B",
    "definition": "Auxiliary data needed for precise orbit determination and non-gravitational force modelling",
    "applicable_missions": [
        "Swarm"
    ],
    "applicable_spacecraft": [
        "Swarm-A",
        "Swarm-B",
        "Swarm-C"
    ],
    "thematic_areas": [
        "HK data"
    ],
    "description": "The SC_XDYN_1B Product contains auxiliary data needed for precise orbit determination and non-gravitational force modelling.",
    "link_files_http": "https://swarm-diss.eo.esa.int/#swarm/Level1b/Latest_baselines/SC_xDYN",
    "link_files_ftp": "ftp://swarm-diss.eo.esa.int/Level1b/Latest_baselines/SC_xDYN",
    "link_vires_gui": "",
    "link_notebook": "",
    "link_hapi": "",
    "variables_table": "Variable,Units,Description,Dim,Type\nTimestamp,-,Time stamp,1,CDF_EPOCH\nSyncStatus,-,Synchronization status,1,CDF_UINT2\na_Sun,m/s2,\"Acceleration due to Solar radiation pressure, S/C frame\",3,CDF_DOUBLE\ne_Sun,-,\"Direction to the Sun, unit vector, S/C frame\",3,CDF_DOUBLE\nm_SC,kg,Actual mass of S/C,1,CDF_DOUBLE\nr_CoG,m,\"Center of gravity, S/C frame\",3,CDF_DOUBLE\nA_head,m2,\"Cross sections of the S/C, orbit frame,front\",3,CDF_DOUBLE\nA_right,m2,\"Cross sections of the S/C, orbit frame,right\",3,CDF_DOUBLE\nA_left,m2,\"Cross sections of the S/C, orbit frame,left\",3,CDF_DOUBLE\nA_down,m2,\"Cross sections of the S/C, orbit frame,down\",3,CDF_DOUBLE\nK_Earth,m2,Downward optical reflectivity of the S/C,3,CDF_DOUBLE\nP_Gas,Pa,Pressure of gas tanks,2,CDF_DOUBLE\nT_Gas,deg C,Temperature of gas tanks,2,CDF_DOUBLE\nFlags_Platform,-,Flags characterizing the S/C platform information,1,CDF_UINT2\ndt_thr,s,Thruster on-time,12,CDF_DOUBLE\nthr_set,-,Flag indicating which thruster branch is active ,1,CDF_UINT2\nf_thr,mN,\"Nominal thrust force of activated thrusters (combined x, y, z)\",3,CDF_DOUBLE\na_centr,m/s2,\"Centrifugal acceleration, S/C frame\",3,CDF_DOUBLE\na_GG,m/s2,\"Gravity gradient acceleration, S/C frame\",3,CDF_DOUBLE\n",
    "related_resources": "",
    "details": "",
    "changelog": ""
}

=== smithara/swarm-handbook-experiment/json/catalog/SW_MIO_SHA_2E.json
{
    "product_id": "SW_MIO_SHA_2E",
    "definition": "Model of polar daily geomagnetic variation caused by ionospheric currents (AMPS model)",
    "applicable_missions": [
        "Swarm"
    ],
    "applicable_spacecraft": [
        "Swarm-A",
        "Swarm-B",
        "Swarm-C"
    ],
    "thematic_areas": [
        "Ionosphere/Magnetosphere"
    ],
    "description": " Model of polar daily geomagnetic variation caused by ionospheric currents (AMPS model)",
    "link_files_http": "https://swarm-diss.eo.esa.int/#swarm/Level2longterm/MIO",
    "link_files_ftp": "ftp://swarm-diss.eo.esa.int/Level2longterm/MIO",
    "link_vires_gui": "https://vires.services?ws=data%3Aapplication/json%2Bgzip%3Bbase64%2CH4sIAMta5mMC/51Va0/bMBT9K1W%2Bro38iF98K4Vuk4AhygYUVVFoTPGUJpWTdiDU/75r00caBoNKVhsf33POzbVz/RyU2i7MWP/StjRFHhy0AhpiHKKg3QoqM9UDnelx9bJ0GxCEeQdhGJcIHfgRIoSGLrq2RugBUzBCpdQwGK2kjoppYjY6rINJh0IseUuHXKKdNaezMPpPPaVgkhV32tFmtkjn46rsFfm9mcxtsop4DgZX8Y/z44v4tPu1G59cxPjQwwtTmrtMw/N9kpUaJIp5lZlcl3VoloxN9QQIdh6JTaa6glp5hcP47Ljnn2yST5zSLWaQarvF3J/Ld1xkhS3HifcJfusqWALa/ywJwNK/tU4BquxcOxnvH1tddhtZdLjT4%2B%2BlsOHGp0Wqs10%2BkAV7i7x09C1pW0aX1k7JUCheF62/T8G%2BvcqPfK5U1w1X5F0Jfdf1plFV4Unin5zULLSdmHwSY88dNrgEvZV0k/m9wZRAlB/gHe3J6xudpetzX69RuxWhd%2BtzHR9fNUwZbOX/LW/2JQ73Ii798nRW5Dqv3FvePgfGnY6ge3o%2B8CfGTHw3%2BRI0D2w%2Bz7Ll6EUCUJucF6XZtJbZdgInmSFJsQqF5ARTytutDuEYCc5IyCJGI6Jku0UjTBDjUYiFJJxE3CWfGrvtsh0UUqoiwpFCTEpgAg2FTCAhOAfJCH4JbA8EigggxiVBYAnhTmw%2BW6kgBRJCQq%2BViEoliZMRXHFGseBCRYIK5jBOMZZSYCWEUkJRp2LN5KHyH1uoKBMYI8qIZEpx7ChEuvRAQlFwUFL4dAjiYKRgRATyl2zkCvfYfTTlTtc%2Bge5czdOXxp0VVbNpwwY9OZK/LPq%2B8/v5SXLn247bFYeRddBoM2uE%2BGOxjnLYqA4Sz4Ucd/xqbXH0yuVDgg4rk0pnmalW31U3mz0ktZvl0CaLojbvPSQ2M/Xr6GzQq81%2BQp2SdA0sl38BYVV2s7sHAAA%3D",
    "link_notebook": "",
    "link_hapi": "",
    "variables_table": "",
    "related_resources": "<ul>\n\t<li><a href=\"https://earth.esa.int/eogateway/activities/amps\">AMPS Project Page</a></li>\n\t<li><a href=\"https://birkeland.uib.no/data/amps/\">WebAMPS</a></li>\n</ul>",
    "details": "<table border=\"1\">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>Product identifier</td>\n\t\t\t<td>MIO_SHA_2E</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Definition</td>\n\t\t\t<td>An empirical model of the Average Magnetic field and Polar current System (<a href=\"https://earth.esa.int/eogateway/activities/amps\">AMPS</a>). See:<br />\n\t\t\t- forward code at <a href=\"https://doi.org/10.5281/zenodo.1182931\">doi: 10.5281/zenodo.1182931</a><br />\n\t\t\t- science paper at <a href=\"https://doi.org/10.1029/2018JA025387\">doi: 10.1029/2018JA025387</a></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Input data</td>\n\t\t\t<td>Swarm magnetic field (MAG-L) measurements, CHAMP magnetic field measurements, model predictions of core, lithospheric and large-scale magnetospheric (including Earth-induced) contributions, taken by the CHAOS geomagnetic field model, OMNI solar wind measurements, F10.7 index</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Input time span</td>\n\t\t\t<td>Entire Swarm mission + entire CHAMP mission</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Spatial representation</td>\n\t\t\t<td>Spherical harmonic expansion in QD/modified apex coordinates, with degree up to 45/65 for poloidal/toroidal magnetic field parts. Spherical harmonic order (in MLT) up to 3</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Time representation</td>\n\t\t\t<td>Time dependence contained in parametrization in terms of external parameters: 20 min average solar wind speed and interplanetary magnetic field, dipole tilt angle, and F10.7 index</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Units</td>\n\t\t\t<td>Magnetic field in nT, horizontal sheet current density in mA/m, vertical current density in &micro;A/m2</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Resolution</td>\n\t\t\t<td>0.1 nT, 1 mA/m, 0.01 &micro;A/m2</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Uncertainty</td>\n\t\t\t<td>See <a href=\"https://doi.org/10.1029/2018JA025387\">doi: 10.1029/2018JA025387</a></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Quality indicator</td>\n\t\t\t<td>N/A</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Data volume</td>\n\t\t\t<td>218 kB</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Data format</td>\n\t\t\t<td>ASCII</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Output data</td>\n\t\t\t<td>Spherical harmonic coefficient</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Output time span</td>\n\t\t\t<td>Model is based on data from entire CHAMP and Swarm missions, but it is in principle valid for any time when solar wind data was available</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Update rate</td>\n\t\t\t<td>Yearly (to be confirmed)</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Latency</td>\n\t\t\t<td>2 months, due to update rate of OMNI data and computation time</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Notes</td>\n\t\t\t<td>&nbsp;</td>\n\t\t</tr>\n\t</tbody>\n</table>\n",
    "changelog": "",
    "fast_processing": "",
    "input_products": [
        "SW_MAGx_LR_1B",
        "SW_MCO_SHA_2X"
    ]
}

=== smithara/swarm-handbook-experiment/json/catalog/SW_PPIxFAC_2F.json
{
    "product_id": "SW_PPIxFAC_2F",
    "definition": "Equatorward boundary of SSFACs and the associated midnight PP index",
    "applicable_missions": [
        "Swarm"
    ],
    "applicable_spacecraft": [
        "Swarm-A",
        "Swarm-B",
        "Swarm-C"
    ],
    "thematic_areas": [
        "Ionosphere/Magnetosphere"
    ],
    "description": "Equatorward boundary of SSFACs and the associated midnight PP index",
    "link_files_http": "https://swarm-diss.eo.esa.int/#swarm/Level2daily/Latest_baselines/PPI/FAC",
    "link_files_ftp": "ftp://swarm-diss.eo.esa.int/Level2daily/Latest_baselines/PPI/FAC",
    "link_vires_gui": "",
    "link_notebook": "",
    "link_hapi": "http://hapi-server.org/servers/#server=VirES-for-Swarm&dataset=SW_OPER_PPIAFAC_2F",
    "variables_table": "Variable,Units,Description,Dim,Type\nTimestamp,ms,\"Time of observation, UTC\",1,CDF_EPOCH\nCounter, ,Swarm orbit counter and quarter orbit (four per Swarm orbit) counter that are based on magnetic coordinates as defined in <a href=\"https://earth.esa.int/eogateway/documents/20142/37627/Swarm-PRISM-Description-of-the-algorithm.pdf\">Swarm PRISM processing algorithm description</a> (Sect. 4.1.2.2),2,CDF_UINT4\nLatitude,deg,Position of the SSFAC boundary in ITRF - Geocentric latitude,1,CDF_DOUBLE\nLongitude,deg,Position of the SSFAC boundary in ITRF - Geocentric longitude,1,CDF_DOUBLE\nRadius,m,Position of the SSFAC boundary in ITRF - Geocentric radius (from the Earth center),1,CDF_DOUBLE\nLatitude_QD,deg,QD latitude of the SSFAC boundary,1,CDF_DOUBLE\nLongitude_QD,deg,QD longitude of the SSFAC boundary,1,CDF_DOUBLE\nMLT,h,Magnetic Local Time of SSFAC boundary,1,CDF_DOUBLE\nL_value,R_E,L-value of the SSFAC boundary,1,CDF_DOUBLE\nSZA,deg,Solar zenith angle of the SSFAC boundary,1,CDF_DOUBLE\ndL, ,Boundary width in Earth radii,1,CDF_DOUBLE\nSigma, ,\"Standard deviation of the linear fit of S at the boundary (Heilig, B. and L\u00fchr, H., doi: 10.5194/angeo-31-529-2013\"),1,CDF_DOUBLE\nPPI,R_E,Midnight Plasmapause index,1,CDF_DOUBLE\nQuality, ,Quality indicators of SSFAC boundary detection,7,CDF_INT1\nTimestamp_ID, ,Time vector of observations,2,CDF_EPOCH\nLatitude_ID,deg,Position in ITRF - Geocentric latitude,2,CDF_DOUBLE\nLongitude_ID,deg,Position in ITRF - Geocentric longitude,2,CDF_DOUBLE\nRadius_ID,m,Position in ITRF - Geocentric radius (from the Earth centre),2,CDF_DOUBLE\nLatitude_QD_ID,deg,QD latitude,2,CDF_DOUBLE\nLongitude_QD_ID,deg,QD longitude,2,CDF_DOUBLE\nMLT_ID,h,Magnetic Local Time,2,CDF_DOUBLE\nL_value_ID, ,L-value in Earth radii,2,CDF_DOUBLE\nSZA_ID,deg,L-value in Earth radii,2,CDF_DOUBLE\nPosition_Quality_ID, ,Vector of quality indicators characterising the detection quality of each single positions,2,CDF_INT1\n",
    "related_resources": "<ul>\n<li><a href=\"https://earth.esa.int/eogateway/activities/swarm-prism\">Activity: Plasmapause Related boundaries in the topside Ionosphere as derived from Swarm Measurements (PRISM)</a></li>\n<li><a href=\"https://earth.esa.int/eogateway/documents/20142/37627/Swarm-PRISM-Product-Definition.pdf\">Swarm PRISM product description</a></li>\n<li><a href=\"https://earth.esa.int/eogateway/documents/20142/37627/Swarm-PRISM-Description-of-the-algorithm.pdf\">Swarm PRISM processing algorithm description</a></li>\n<li><a href=\"https://earth.esa.int/eogateway/documents/20142/37627/Swarm-PRISM-Validation-Report.pdf\">Swarm PRISM validation report</a></li>\n</ul>",
    "details": "<table border=\"1\">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>Product identifier</td>\n\t\t\t<td>PPIxFAC_2F</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Definition</td>\n\t\t\t<td>Equatorward boundary of SSFACs and the associated midnight PP index</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Input data</td>\n\t\t\t<td>FACxTMS_2F<sup>1</sup>, EFIx_LP_1B<sup>1</sup>, TECxTMS_2F<sup>1</sup>, AOBxFAC_2F<sup>1</sup>, AUXxORBCNT</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Input time span</td>\n\t\t\t<td>Up to one year<sup>2</sup></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Spatial representation</td>\n\t\t\t<td>One geographic and QD-latitude/longitude pair, the McIlwain L-value as well as radius for each output position at the nearest FAC measurement for each trough crossing, i.e., up to four per orbit</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Time representation</td>\n\t\t\t<td>Up to four records per orbit (up to one record per orbit quarter)</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Units</td>\n\t\t\t<td>see at Output Data below</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Resolution</td>\n\t\t\t<td>0.1 degree for coordinates, 0.01 for L-value</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Uncertainty</td>\n\t\t\t<td>~1 degree for coordinates, ~0.1 for L-value</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Quality indicator</td>\n\t\t\t<td><strong>Quality</strong> vector flag values are integers ranging from 3 to -1. Positive values indicate good or acceptable observation, while -1 means a likely false observation. For all flags, a 0 value means that the information needed to derive the flag is not available. In general, greater numbers indicate higher quality. A detailed description of the derivation of these flags is given in <a href=\"https://earth.esa.int/eogateway/documents/20142/37627/Swarm-PRISM-Description-of-the-algorithm.pdf\">Swarm PRISM processing algorithm description</a> (see also related resources)</br>\n<strong>Position_Quality_ID</strong> describes the overall quality of the corresponding boundary/position identified by ID. These flags are defined based on the parameter\u2019s sigma and SZA. 3: sig-ma<0.25, 2: 0.25\u2264sigma<0.5, 1: 0.5\u2264sigma AND SZA>90\u00b0, -1: 0.5\u2264sigma AND SZA\u226490\u00b0.\n</td>\n\t\t</tr>\n<tr>\n\t\t\t<td>Data volume</td>\n\t\t\t<td>Up to 1.9 MB</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Output data</td>\n\t\t\t<td>See file contents</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Output time span</td>\n\t\t\t<td>Up to one year<sup>2</sup></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Latency</td>\n\t\t\t<td>< 5 minutes</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Update rate</td>\n\t\t\t<td>Daily</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Notes</td>\n\t\t\t<td><sup>1</sup> Version information of Input Data are available in the CDF global attributes.</br><sup>2</sup> Product always contains data from the start of the first boundary crossing of the first day until the end of the last boundary-crossing starting the latest day available for that year, i.e., may contain data from the next day if boundary crossing occurs around midnight.</br><sup>3</sup> The meaning of ID: 1 \u2013 Equatorward edge of SSFAC boundary; 2 \u2013 Poleward edge of SSFAC boundary.</br><sup>4</sup> NaN values: if an ID is not identified Timestamp_ID is set to {the value of} Timestamp and corresponding variable values will be set to NaNs.</br></td>\n\t\t</tr>\n\t</tbody>\n</table>",
    "changelog": "",
    "fast_processing": "",
    "input_products": [
        "SW_AOBxFAC_2F",
        "SW_AUXxORBCNT",
        "SW_EFIx_LP_1B",
        "SW_FACxTMS_2F",
        "SW_TECxTMS_2F"
    ]
}

=== smithara/swarm-handbook-experiment/json/catalog/SW_MCO_SHA_2Y.json
{
    "product_id": "SW_MCO_SHA_2Y",
    "definition": "Model of the core field, related to SW_CFW_SHA_2Y",
    "applicable_missions": [
        "Swarm"
    ],
    "applicable_spacecraft": [
        "Swarm-A",
        "Swarm-B",
        "Swarm-C"
    ],
    "thematic_areas": [
        "Core field"
    ],
    "description": "Series of core field models provided in terms of Gauss coefficients + covariance matrices + standard deviations of Gauss coefficients.\n\nRelated to SW_CFW_SHA_2Y",
    "link_files_http": "https://swarm-diss.eo.esa.int/#swarm/Level2longterm/MCO",
    "link_files_ftp": "ftp://swarm-diss.eo.esa.int/#swarm/Level2longterm/MCO",
    "link_vires_gui": "",
    "link_notebook": "",
    "link_hapi": "",
    "variables_table": "",
    "related_resources": "Ropp, G., Lesur, V., Baerenzung, J., and Holschneider, M. (2020), Sequential modelling of the Earth\u2019s core magnetic field, Earth, Planets and Space, 72(1) :153, doi :10.1186/s40623-020- 01230-1\n\nRopp, G. and Lesur, V. (2022), Mid-latitude and equatorial core surface flow variations derived from observatory and satellite magnetic data, Geophys J. Int., under review",
    "details": "<table border=\"1\">\n\t<thead>\n\t\t<tr>\n\t\t\t<th style=\"text-align: left;\">Product identifier</th>\n\t\t\t<th style=\"text-align: left;\">MCO_SHA_2Y</th>\n\t\t</tr>\n\t</thead>\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>Definition</td>\n\t\t\t<td>&bull; Core field Gauss coefficients stored in the .shc file<br />\n\t\t\t&bull; The standard deviations of Gauss coefficients are stored in the .std file<br />\n\t\t\t&bull; The covariance matrices are stored in the .cov file</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Input Data</td>\n\t\t\t<td>Derived from Swarm Level 1b MAGX_LR_1B, the Oersted, Champ, CryoSat data and the Magnetic Observatories data</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Input Time Span</td>\n\t\t\t<td>01/01/1999 to latest Swarm data processed</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Spatial representation</td>\n\t\t\t<td>Spherical harmonic expansion up to degree and order 18</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Time representation</td>\n\t\t\t<td>Snapshots built sequentially through a Kalman filter with a time span of 0.25 &times; 365.25 days</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Units</td>\n\t\t\t<td>nT</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Resolution</td>\n\t\t\t<td>Temporal resolution: 0.25 &times; 365.25 days<br />\n\t\t\tSpatial resolution: Max SH degree 18</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Uncertainty</td>\n\t\t\t<td>See MCO_SHA_2Y cov and std files</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Quality indicator</td>\n\t\t\t<td>&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Data volume</td>\n\t\t\t<td>~1MB</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Data format</td>\n\t\t\t<td>The shc file is in SHC format<br />\n\t\t\tThe std file is in ASCII table format (see description below)<br />\n\t\t\tThe cov file is in ASCII format (see description below)</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Output Data</td>\n\t\t\t<td>The product consists in three files<br />\n\t\t\t<br />\n\t\t\t<strong>MCO_SHA_2Y shc and std file</strong><br />\n\t\t\tThe format used has been set in accordance with the usual SHC format defined for this type of files. Units of Gauss coefficients are nT<br />\n\t\t\tWith a very similar format the standard deviations of the Gauss coefficients are provided in an independent file with the extension *.std<br />\n\t\t\tThe only difference in the format is on the first line where the B-spline order, and the number of intervals between spline knots, are not indicated. Units of standard deviations are nT.<br />\n\t\t\t<br />\n\t\t\t<strong>MCO_SHA_2Ycov file</strong><br />\n\t\t\tIn this independent file with the extension *.cov, the covariance matrice upper triangles (i.e. variances and covariances) is provided.<br />\n\t\t\tA covariance matrice being symmetric no information is lost.<br />\n\t\t\tThe format of the file is:<br />\n\t\t\t&bull; On the first line the series of dates (in decimal years) of the mean snapshot core field models associated with the covariance matrices.<br />\n\t\t\t&bull; On the next lines are indicated: the row index of the covariance matrix, the column index of the covariance matrix, followed by the time series of variances or covariances in the order given by the first line dates. Units of matrix elements are nT<sup>2</sup>.</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Output time span</td>\n\t\t\t<td>From earliest to latest epoch compatible with input data</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Update rate</td>\n\t\t\t<td>Yearly</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Latency</td>\n\t\t\t<td>One year</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>Notes</td>\n\t\t\t<td>&nbsp;</td>\n\t\t</tr>\n\t</tbody>\n</table>\n",
    "changelog": "",
    "fast_processing": "",
    "input_products": [
        "SW_MAGx_LR_1B"
    ]
}

=== smithara/swarm-handbook-experiment/json/catalog/future/SW_ACCxDISi2_.json
{
    "product_id": "SW_ACCxDISi2_",
    "definition": "-",
    "thematic_areas": [],
    "description": "-",
    "link_files_http": "",
    "link_files_ftp": "",
    "link_vires_gui": "",
    "link_notebook": "",
    "link_hapi": "",
    "variables_table": "",
    "related_resources": "",
    "details": ""
}
